#============================================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# Description: Build OpenWrt system image from source
#============================================================================================

name: Build OpenWrt remark image

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:

      kernel_repo:
        description: "Set the kernel repository"
        required: false
        default: "ophub/kernel"
        type: choice
        options:
          - ophub/kernel
      openwrt_storage:
        description: "Select image storage type."
        required: false
        default: "save"
        type: choice
        options:
          - save
          - temp
env:
  TZ: Etc/UTC
  CCACHE_DIR: /builder/openwrt/.ccache

jobs:
  setup:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set build matrix based on source_branch input
        id: set-matrix
        run: |
          MATRIX='{"include":[{"branch":"immortalwrt_master"}]}'
          echo "matrix=${MATRIX}" >> "${GITHUB_OUTPUT}"

  build:
    needs: setup
    runs-on: ubuntu-24.04
    if: ${{ github.event.repository.owner.id == github.event.sender.id }}

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}

    name: build-${{ matrix.branch }}

    env:
      FEEDS_CONF: config/${{ matrix.branch }}/feeds.conf.default
      CONFIG_FILE: config/${{ matrix.branch }}/config
      DIY_P1_SH: config/${{ matrix.branch }}/diy-part1.sh
      DIY_P2_SH: config/${{ matrix.branch }}/diy-part2.sh
      CUSTOM_SCRIPT_1: config/${{ matrix.branch }}/custom_script_1.sh
      CUSTOM_SCRIPT_2: config/${{ matrix.branch }}/custom_script_2.sh
      CUSTOM_SCRIPT_3: config/${{ matrix.branch }}/custom_script_3.sh

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Initialize the build environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt -yqq purge firefox
          sudo -E apt -yqq update
          sudo -E apt -yqq full-upgrade
          sudo -E apt -yqq autoremove --purge
          sudo -E apt -yqq autoclean
          sudo -E apt -yqq clean
          sudo -E apt -yqq install dos2unix libfuse-dev libc6-dev-i386 lib32z1 lib32stdc++6 patchelf
          sudo -E systemctl daemon-reload
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Create virtual disk for extended storage
        run: |
          sudo mkdir /builder
          sudo chown runner:runner /builder
          df -Th
          lsblk
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Clone source code [ ${{ matrix.branch }} ]
        id: codes
        working-directory: /builder
        run: |
          # Determine the OpenWrt source code repository
          if [[ "${{ matrix.branch }}" =~ ^openwrt ]]; then
              REPO_URL="https://github.com/openwrt/openwrt"
          elif [[ "${{ matrix.branch }}" =~ ^lede ]]; then
              REPO_URL="https://github.com/coolsnowwolf/lede"
          elif [[ "${{ matrix.branch }}" =~ ^immortalwrt ]]; then
              REPO_URL="https://github.com/immortalwrt/immortalwrt"
          else
              echo "Error: Unknown source code repository."
              exit 1
          fi
          source_branch_input="${{ matrix.branch }}"
          REPO_NAME="${source_branch_input%_*}"
          REPO_BRANCH="${source_branch_input##*_}"

          # Clone the source code repository
          git clone -q --single-branch --depth=1 --branch=owrt https://github.com/VIKINGYFY/immortalwrt openwrt
          ln -sf /builder/openwrt ${{ github.workspace }}/openwrt
          ln -sf /builder/openwrt /home/runner/work/_actions/ophub/amlogic-s9xxx-openwrt/main/openwrt

          # Export build metadata
          echo "build_tag=OpenWrt_${{ matrix.branch }}_${{ inputs.openwrt_storage }}_$(date +"%Y.%m")" >> ${GITHUB_ENV}
          echo -e "REPO_URL: [ ${REPO_URL} ]\nREPO_BRANCH: [ ${REPO_BRANCH} ]\nREPO_NAME: [ ${REPO_NAME} ]"
          df -hT ${PWD}
          echo "REPO_URL=${REPO_URL}" >> ${GITHUB_ENV}
          echo "REPO_NAME=${REPO_NAME}" >> ${GITHUB_ENV}
          echo "REPO_BRANCH=${REPO_BRANCH}" >> ${GITHUB_ENV}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Package OpenWrt for target boards
        uses: ophub/amlogic-s9xxx-openwrt@main
        with:
          openwrt_path: https://github.com/legna05/amlogic-s9xxx-openwrt/releases/download/OpenWrt_immortalwrt_master_save_2026.06/immortalwrt-armsr-armv8-rootfs.tar.gz
          openwrt_ip: 192.168.1.99
          openwrt_board: dg3399
          openwrt_kernel: 6.12.y
          auto_kernel: true
          kernel_repo: ophub/kernel
          kernel_usage: stable
          builder_name: angel

      - name: Upload packaged OpenWrt to Release
        uses: ophub/upload-to-releases@main
        if: ${{ env.PACKAGED_STATUS == 'success' && !cancelled() }}
        with:
          tag: ${{ env.build_tag }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allow_updates: true
          remove_artifacts: false
          replaces_artifacts: true
          make_latest: true
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### OpenWrt Image Information
            - Default IP: `192.168.1.1`
            - Default username: `root`
            - Default password: `password`
            - Default WIFI name: `OpenWrt`
            - Default WIFI password: `none`
            ### Install to EMMC
            - Login to OpenWrt → `System` → `Amlogic Service` → `Install OpenWrt`
            ### OpenWrt source code
            - [${{ env.REPO_NAME }}](${{ env.REPO_URL }}/tree/${{ env.REPO_BRANCH }})
            ### Applicable Platform
            - 🐧 `arm64`
            - 🐋 Docker image: https://hub.docker.com/u/ophub
