#============================================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# Description: Build OpenWrt system image from source
#============================================================================================

name: Build OpenWrt system image

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Select the source branch"
        required: false
        default: "immortalwrt_master"
        type: choice
        options:
          - all
          - openwrt_main
          - lede_master
          - immortalwrt_master
      openwrt_ip:
        description: "Set OpenWrt default IP address."
        required: false
        default: "192.168.1.99"
      use_ccache:
        description: "Auto use ccache."
        required: false
        default: true
        type: boolean
      openwrt_storage:
        description: "Select image storage type."
        required: false
        default: "save"
        type: choice
        options:
          - save
          - temp

env:
  TZ: Etc/UTC
  CCACHE_DIR: /builder/openwrt/.ccache

jobs:
  setup:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set build matrix based on source_branch input
        id: set-matrix
        run: |
          if [[ "${{ inputs.source_branch }}" == "all" ]]; then
            MATRIX='{"include":[{"branch":"openwrt_main"},{"branch":"lede_master"},{"branch":"immortalwrt_master"}]}'
          else
            MATRIX='{"include":[{"branch":"${{ inputs.source_branch }}"}]}'
          fi
          echo "matrix=${MATRIX}" >> "${GITHUB_OUTPUT}"

  build:
    needs: setup
    runs-on: ubuntu-24.04
    if: ${{ github.event.repository.owner.id == github.event.sender.id }}

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}

    name: build-${{ matrix.branch }}

    env:
      FEEDS_CONF: config/${{ matrix.branch }}/feeds.conf.default
      CONFIG_FILE: config/${{ matrix.branch }}/config
      DIY_P1_SH: config/${{ matrix.branch }}/diy-part1.sh
      DIY_P2_SH: config/${{ matrix.branch }}/diy-part2.sh
      CUSTOM_SCRIPT_1: config/${{ matrix.branch }}/custom_script_1.sh
      CUSTOM_SCRIPT_2: config/${{ matrix.branch }}/custom_script_2.sh
      CUSTOM_SCRIPT_3: config/${{ matrix.branch }}/custom_script_3.sh

    steps:
      - name: Check Server Performance(检查服务器性能)
        run: |
          echo "警告⚠"
          echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
          echo -e "已知CPU型号（降序）：7763，8370C，8272CL，8171M，E5-2673 \n"
          echo "--------------------------CPU信息--------------------------"
          echo "CPU物理数量：$(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
          echo -e "CPU核心信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
          echo "--------------------------内存信息--------------------------"
          echo "已安装内存详细信息："
          echo -e "$(sudo lshw -short -C memory | grep GiB) \n"
          echo "--------------------------硬盘信息--------------------------"
          echo "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Initialize the build environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt -yqq purge firefox
          sudo -E apt -yqq update
          sudo -E apt -yqq full-upgrade
          sudo -E apt -yqq autoremove --purge
          sudo -E apt -yqq autoclean
          sudo -E apt -yqq clean
          sudo -E apt -yqq install dos2unix libfuse-dev patchelf
          sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
          sudo -E systemctl daemon-reload
          sudo -E timedatectl set-timezone "Asia/Shanghai"
          
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Create virtual disk for extended storage
        run: |
          sudo mkdir /builder
          sudo chown runner:runner /builder
          df -Th
          lsblk
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Clone source code [ ${{ matrix.branch }} ]
        id: codes
        working-directory: /builder
        if: ${{ steps.init.outputs.status == 'success' && !cancelled() }}
        run: |
          # Determine the OpenWrt source code repository
          if [[ "${{ matrix.branch }}" =~ ^openwrt ]]; then
              REPO_URL="https://github.com/openwrt/openwrt"
          elif [[ "${{ matrix.branch }}" =~ ^lede ]]; then
              REPO_URL="https://github.com/coolsnowwolf/lede"
          elif [[ "${{ matrix.branch }}" =~ ^immortalwrt ]]; then
              REPO_URL="https://github.com/VIKINGYFY/immortalwrt"
          else
              echo "Error: Unknown source code repository."
              exit 1
          fi
          source_branch_input="${{ matrix.branch }}"
          REPO_NAME="${source_branch_input%_*}"
          REPO_BRANCH="owrt"

          # Clone the source code repository
          git clone -q --single-branch --depth=1 --branch=${REPO_BRANCH} ${REPO_URL} openwrt
          ln -sf /builder/openwrt ${{ github.workspace }}/openwrt
          tree /home/runner/work/
          ln -sf /builder/openwrt $GITHUB_WORKSPACE/openwrt

          # Export build metadata
          echo "build_tag=OpenWrt_${{ matrix.branch }}_${{ inputs.openwrt_storage }}_$(date +"%Y.%m")" >> ${GITHUB_ENV}
          echo -e "REPO_URL: [ ${REPO_URL} ]\nREPO_BRANCH: [ ${REPO_BRANCH} ]\nREPO_NAME: [ ${REPO_NAME} ]"
          df -hT ${PWD}
          echo "REPO_URL=${REPO_URL}" >> ${GITHUB_ENV}
          echo "REPO_NAME=${REPO_NAME}" >> ${GITHUB_ENV}
          echo "REPO_BRANCH=${REPO_BRANCH}" >> ${GITHUB_ENV}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Load custom feeds
        run: |
          [[ -f "${FEEDS_CONF}" ]] && cp -f ${FEEDS_CONF} openwrt/feeds.conf.default
          chmod +x ${DIY_P1_SH}
          chmod +x ${CUSTOM_SCRIPT_1}
          chmod +x ${CUSTOM_SCRIPT_2}
          chmod +x ${CUSTOM_SCRIPT_3}
          cd openwrt/
          ${{ github.workspace }}/${DIY_P1_SH}
          
          # GitHub Action 移除国内下载源
          PROJECT_MIRRORS_FILE="./scripts/projectsmirrors.json"
          if [ -f "$PROJECT_MIRRORS_FILE" ]; then
            sed -i '/.cn\//d; /tencent/d; /aliyun/d' "$PROJECT_MIRRORS_FILE"
          fi

      - name: 添加自定义feed
        run: cd openwrt/ && ${{ github.workspace }}/${CUSTOM_SCRIPT_1}

      - name: Update feeds
        run: cd openwrt/ && ./scripts/feeds update -a

      - name: 提前安装feed
        run: cd openwrt/ && ${{ github.workspace }}/${CUSTOM_SCRIPT_2}

      - name: Install feeds
        run: cd openwrt/ && ./scripts/feeds install -a

      - name: Load custom configuration
        run: |
          [[ -d "files" ]] && mv -f files openwrt/files
          [[ -e "${CONFIG_FILE}" ]] && cp -f ${CONFIG_FILE} openwrt/.config
          chmod +x ${DIY_P2_SH}
          cd openwrt/
          ${{ github.workspace }}/${DIY_P2_SH} "${{ inputs.openwrt_ip }}" "${{ inputs.use_ccache }}"

      - name: 自定义添加config
        run: cd openwrt/ && ${{ github.workspace }}/${CUSTOM_SCRIPT_3}

      - name: Download package
        id: package
        run: |
          cd openwrt/
          make defconfig
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -type f -size -1024c -exec rm -f {} \;
          find dl -type d -empty -exec rmdir {} \;

      - name: Get OpenWrt source commit hash
        id: openwrthash
        run: |
          # Get the latest source hash from the kernel repository
          repo_path="$(echo "${{ env.REPO_URL }}" | awk -F"github.com/" '{print $2}')"
          api_url="https://api.github.com/repos/${repo_path}/git/ref/heads/${{ env.REPO_BRANCH }}"
          echo "api_url:$api_url"
          source_hash=$(curl -fsSL -m 20 \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              ${api_url} |
              jq -r '.object.sha'
          )
          echo "source_hash_from_api:$source_hash"
          
          [[ -z "${source_hash}" || "${source_hash}" == "null" ]] && source_hash="${{ github.sha }}"
          echo "source_hash=${source_hash}"
          echo "source_hash=${source_hash}" >> ${GITHUB_ENV}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Cache ccache
        uses: actions/cache@v5
        with:
          path: /builder/openwrt/.ccache
          key: openwrt-${{ env.REPO_NAME }}-${{ env.source_hash }}
          restore-keys: |
            openwrt-${{ env.REPO_NAME }}-

      - name: Cache Tool
        id: cache-tool
        uses: actions/cache@v5
        with:
          path: |
            /builder/openwrt/staging_dir/tool*
            /builder/openwrt/staging_dir/host*
          key: openwrt-tool-${{ env.REPO_NAME }}
          restore-keys: |
            openwrt-tool-

      - name: Update Caches
        if: ${{steps.cache-tool.outputs.cache-hit == 'true'}}
        run: |
          if [ -d "/builder/openwrt/staging_dir" ]; then
            find "/builder/openwrt/staging_dir" -type d -name "stamp" -not -path "*target*" | while read -r DIR; do
              find "$DIR" -type f -exec touch {} +
            done
            mkdir -p /builder/openwrt/tmp && echo "1" > /builder/openwrt/tmp/.build
            echo "toolchain skiped done!"
          else
            echo "caches missed!"
          fi

      - name: Compile the OpenWrt firmware
        id: compile
        run: |
          cd openwrt/
          echo -e "Compiling with $(nproc) threads"
          make -j$(($(nproc) + 1)) || make -j1 || make -j1 V=s

          echo -e "ccache statistics:"
          ccache -s 2>/dev/null
          echo -e "ccache directory size:"
          du -sh $(pwd)/.ccache 2>/dev/null || echo "No ccache directory found."

          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Clean up build files and reclaim disk space
        id: clean
        if: ${{ steps.compile.outputs.status == 'success' && !cancelled() }}
        run: |
          # Clean up build artifacts and reclaim disk space
          cd openwrt/
          [[ -d "output" ]] || mkdir output
          cp -f bin/targets/*/*/*rootfs.tar.gz output/
          cp -f .config output/config

          # Export build metadata
          df -hT ${PWD}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Upload OpenWrt rootfs to Release
        uses: ophub/upload-to-releases@main
        if: ${{ steps.clean.outputs.status == 'success' && !cancelled() }}
        with:
          tag: ${{ env.build_tag }}
          artifacts: openwrt/output/*
          allow_updates: true
          remove_artifacts: false
          replaces_artifacts: true
          make_latest: true
          gh_token: ${{ secrets.GITHUB_TOKEN }}